# Generated by Django 4.1 on 2024-03-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='theme',
            field=models.ManyToManyField(to='services.showtheme'),
        ),
    ]
